spring:
  application:
    name: ${SPRING_APPLICATION_NAME:MrCoolSoftApplication}
  config:
    import: application_prod.yml
  profiles:
    default: default
    active: prod

  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:mrcoolbank}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8180/realms/MrCool/protocol/openid-connect/certs}
        #opaque:
         # introspection-uri: ${INTROSPECT_URI:http://localhost:8180/realms/MrCool/protocol/openid-connect/token/introspect}
         # introspection-client-id: ${INTROSPECT_ID:mrcoolbankintrospect}
         # introspection-client-secret: ${INTROSPECT_SECRET:qwXsO6IMdDTN7HYEyjssp13GwIjijvSG}
logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${LOGLEVEL_SPRING_SECURITY:trace}

server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:2m}

