spring:
  application:
    name: ${SPRING_APPLICATION_NAME:MrCoolSoftApplication}s

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${LOGLEVEL_SPRING_SECURITY:trace}